site_name: Team Jakoubek |> Technotes
site_author: Oliver Jakoubek
site_url: https://technotes.jakoubek.net/

nav:
  - Start:
    - 'index.md'
    - Tags: tags.md
  - SQL:
    - 'sql/index.md'
    - 'Stored Procedures': sql/stored-procedures.md
    - Import Excel in Datenbank: sql/datenbank-import-aus-excel.md
  - 'SQL Anywhere':
    - 'sql-anywhere/index.md'
    - Administration:
      - 'Datenbank anlegen': sql-anywhere/datenbank-anlegen.md
      - 'Datenbank starten': sql-anywhere/datenbank-starten.md
      - 'Transaktionslog': sql-anywhere/transaktionslog.md
      - 'Version herausfinden': sql-anywhere/version-herausfinden.md
      - 'Datenbank entladen': sql-anywhere/datenbank-entladen.md
      - 'Datenbank-Neuaufbau': sql-anywhere/datenbank-rebuild.md
      - iSQL: sql-anywhere/isql.md
    - 'Backup und Wiederherstellung':
      - 'Inkrementelle Sicherung': sql-anywhere/inkrementelle-sicherung.md
      - 'Live-Sicherung': sql-anywhere/live-sicherung.md
      - 'Clientseitige Sicherung': sql-anywhere/clientseitige-sicherung.md
      - Archivsicherung: sql-anywhere/archivsicherung.md
    - Entwicklung:
      - Tabellen: sql-anywhere/table.md
      - 'System-Views und -Prozeduren': sql-anywhere/system.md
      - Zeilengenerator: sql-anywhere/zeilengenerator.md
      - 'Verschiedene Funktionen': sql-anywhere/verschiedene-funktionen.md
      - Aktualisierungs-Timestamps: sql-anywhere/timestamps.md
      - 'Request Logging': sql-anywhere/request-logging.md
  - Go:
    - 'go/index.md'
    - Structs: go/struct.md
    - Files: go/files.md
    - Datum: go/date.md
    - Strings: go/string.md
    - Loops: go/loops.md
    - Switch: go/switch.md
    - Maps: go/maps.md
    - JSON: go/json.md
    - Webserver: go/webserver.md
  - Xojo:
    - 'xojo/index.md'
    - Arrays: xojo/arrays.md
    - Dictionaries: xojo/dictionary.md
    - Fenster: xojo/windows.md
    - Listbox: xojo/listbox.md
    - Dialoge: xojo/dialog.md
    - Folderitem: xojo/folderitem.md
    - Loops: xojo/loops.md
    - Switch-Statement: xojo/switch.md
    - Datenbank: xojo/datenbank.md
  - Misc:
    - 'misc/index.md'
    - Texteditor: misc/texteditor.md
    - MkDocs: misc/mkdocs.md
    - Markdown: misc/markdown.md
    - Pushover: misc/pushover.md
  - 'Über':
    - 'info/index.md'

theme:
  name: material
  language: de
  palette:
    scheme: default
    primary: blue
    accent: indigo
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  highlightjs: true

copyright: Copyright &copy; 2022 <a href="https://www.jakoubek.net/?ref=tnt">Oliver Jakoubek Software & Beratung</a>

plugins:
  - tags:
      tags_file: tags.md
  - search:
      lang:
        - de
        - en

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - meta
